version: '3.7'

services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - db1
      - db2
    environment:
      core.tenants.file-name: /tenants.json
    networks:
      - backend
    volumes:
      - ./docker/tenants.json:/tenants.json

  db1:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3316:3306"
    restart: always
    environment:
      MYSQL_DATABASE: database1
      MYSQL_ROOT_PASSWORD: 9gtKfqdJeKuvqakK
    volumes:
      - ./scripts/database1.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend  

  db2:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3317:3306"
    restart: always
    environment:
      MYSQL_DATABASE: database2
      MYSQL_ROOT_PASSWORD: 9gtKfqdJeKuvqakK
    volumes:
      - ./scripts/database2.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend  

networks:
  backend:

volumes:
  db-data:
